googleAnalytics = "UA-154884741-1"
languageCode = "en-us"
title = "Devtron Labs tutorial"
theme = "ace-documentation"
toc = true
disableSearch = false
[outputs]
home = [ "HTML", "RSS", "JSON"]
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
